version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - chroma_data:/app/chroma_data
    env_file:
      - .env
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false

volumes:
  chroma_data:
